# This Jupyter Notebook shows how to use the library to carry out the structural analysis
## Also this is my first time trying out the github and vscode


## 1. material_type()

In [1]:
from tuda_structural_analysis import material_type
help (material_type)

Help on function material_type in module tuda_structural_analysis:

material_type(stiffness_matrix)
    Checks the given stiffness matrix for the type of linearity, whether the material is isotropic, orthotropic, monotropic, transversal isotropic or fully anisotropic
    
    Parameters
    ----------
    stiffness_matrix: numpy array, 3x3 or 6x6 matrix
        The Stifness matrix in its standard form, a 3x3 matrix for 2d problems and a 6x6 matrix for 3d problems
    
    Returns
    -------
    output: string
        Tells the user if the material is isotropic, orthotropic, monotropic, transversal isotropic or fully anisotropic



In [2]:
import numpy as np
stiffness_matrix = np.array([
    [1,2,3,4,5,6],
    [7,8,9,10,11,12],
    [13,14,15,16,17,18],
    [19,20,21,22,23,24],
    [25,26,27,28,29,30],
    [31,32,33,34,35,36]
])
material_type(stiffness_matrix)

'The material is fully anisotropic and requires 21 independent material properties'

## 2. Stiffness and complaince matrix for plane strain and plane stress conditions

In [3]:
from tuda_structural_analysis import *
help(stiffness_matrix_plane_strain)

Help on function stiffness_matrix_plane_strain in module tuda_structural_analysis:

stiffness_matrix_plane_strain(material)
    Calculates the Stiffness matrix for an isotropic material for the plane strain condition
    
    Parameters
    ----------
    material : list
        The list of isotropic material properties in the form (E,nu)
    
    Returns
    -------
    stiffness_matrix : numpy array, 3x3 matrix
        Returns the stifness matrix in its standard form as described in the literature by Prof. Mittelstedt



In [4]:
E = 5000.0
nu = 0.25
material = (E,nu)
stiffness_matrix_plane_strain(material)

array([[6000., 2000.,    0.],
       [2000., 6000.,    0.],
       [   0.,    0., 2000.]])

In [5]:
stiffness_matrix_plane_stress(material)

array([[5333.33333333, 1333.33333333,    0.        ],
       [1333.33333333, 5333.33333333,    0.        ],
       [   0.        ,    0.        , 2000.        ]])

In [6]:
complaince_matrix_plane_strain(material)

array([[ 1.875e-04, -6.250e-05,  0.000e+00],
       [-6.250e-05,  1.875e-04,  0.000e+00],
       [ 0.000e+00,  0.000e+00,  5.000e-04]])

In [7]:
complaince_matrix_plane_stress(material)

array([[ 2.e-04, -5.e-05,  0.e+00],
       [-5.e-05,  2.e-04,  0.e+00],
       [ 0.e+00,  0.e+00,  5.e-04]])